name: Build OTT Navigator M3U

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build-m3u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run M3U processor
        run: python process.py
        env:
          M3U_URL: ${{ secrets.M3U_URL }}

      - name: Commit and push output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ott-jstar.m3u
          git commit -m "Update ott-jstar.m3u [skip ci]" || echo "No changes"
          git push
